jquense/react-big-calendar

package.json
src/Calendar.jsx

This already works, no code change is needed; this just fixes the warning you get by doing so.
This turns out to be very useful for formatting button text or replacing it with an icon.

Use the node type for messages instead of string

---

src/Toolbar.jsx

Hi!
I was wondering if it would make sense not to display the views on the right side, in the toolbar if you pass only one view. Let's say you only want a monthly view, it doesn't really male sense to show only a month tab, not doing anything when clicking on it, and it doesn't show any valuable information.

Do not show view toolbar if only one view is specified

---

package.json

Current issue:
$ npm i --save react@15
npm ERR! peerinvalid The package react@15.0.1 does not satisfy its siblings' 
peerDependencies requirements!
npm ERR! peerinvalid Peer react-big-calendar@0.9.8 wants react@^0.14.0-beta1

Update React peerDependency to allow working with v15.x (15.0.1)

---

examples/demos/cultures.js
package.json
src/localizers/globalize.js

This PR resolves issue #78  where the evaluation of first day of the week fails on every Sunday (for en-GB locale at least). On Sundays the first day of the week was evaluated as Saturday instead of Monday. 
The PR is an update to the ```firstOfWeek``` function in ```src/localizers/globalize.js``` and it uses the CLDR supplemental data to correctly retrieve the first day of the week. Failing to use this method, there is a fallback to using the original Math based approach to determine the first day. 
Another change is an update to packages.json file, which removes the ```files``` key. The problem with that was that having files there, meant any ```npm install``` from github resulted in JUST those files listed, and none of the src files. Apparently this is a common problem (also exists in …

Fix first day of the week evaluation when using Globalize

---

package.json

My previous PR removed files from packages.json as it was preventing the 
installation of the package from github. Basically only the files included were 
pulled from git when going that route. Removing files caused all files to be 
pulled from git when doing npm install. This however is also undesirable as 
you'd only want distributable files going to the npm process when installing 
from npm.
So, in short, it should be your decision how to proceed with this, not mine, 
so I'm reverting the packages file to how it was. If stays as is, it won't be 
possible to install this package from github but that is not necessarily a bad 
thing. One can always fork, update packages, and use the fork to install until 
dev is over. As well, there are probably better options to cater both to github 
and …

revert back package.json to include the files key

---

src/Calendar.jsx

Allows a custom Toolbar component to be passed in and used in place of the default.  This makes it easy to move around the date and view navigation buttons. 
Sample custom toolbar:
@jquense

allow a custom toolbar to be passed in

---

src/TimeGrid.jsx

This should fix issue #36 (the week view issue).
**Note**:  I'm not sure of the potential collateral this fix could bring up. I manually tested that it works for my use cases (month and week views) so there may not be any. Should we start adding functional tests?
**Second Note**: I needed to update some unrelated code because the `npm test` command was failing. There was a lint error.

Fix full week span event being truncated on last day of the week.

---

examples/App.js
examples/demos/customView.js
src/Calendar.jsx

Fixes #97 
Do follow the comments of #93 
I did not manage to set the propType good in `src/utils/propTypes.js`, can you help me with that ? 
Doing this, I tried to extends the `Week` view, but it was not as easy as I though, so I had to reimplement a full view. The fact is that we can not extends the `range` method. I do not search very well for that as it is not the purpose of this code, but it might be a good future evolution.

allow to pass custom views

---

src/localizers/moment.js

In Globalize `dd` is the numeric day of the month but in Moment it's the [short weekday](http://momentjs.com/docs/#/displaying/format/), meaning that the day header was rendered as 'Monday May Mo' instead of 'Monday May 01' when using Moment.

Fix dayHeaderFormat when using Moment.js

---

package.json

This PR enables npm-based css imports for libraries like [npm-css](https://github.com/defunctzombie/npm-css), [postcss-import](https://github.com/postcss/postcss-import#postcss-import), [rework-import](https://github.com/reworkcss/rework-npm) so you can write:
```css
@import "react-big-calendar";
```
instead of 
```css
@import "react-big-calendar/lib/css/react-big-calendar.css";
```
r? @jquense

Add style key to package.json

---

src/Calendar.jsx

Just adds the `step` prop from `src/TimeGrid` to the propTypes of `src/Calendar` so that it appears in the documentation - it's a super useful prop to know about. Sets a default value of 30, much like in `src/TimeGrid` since half hour increments seem to be the default elsewhere in the code.

Documentation: 'step' prop

---

examples/demos/selectable.js
src/Calendar.jsx
src/TimeGrid.jsx

I added a new prop scrollTime so that the TimeGrid view is initially scrolled down to a specified hour on every mount or change of prev/next week. Let me know if I need to add any checks!
Original prop: http://fullcalendar.io/docs/agenda/scrollTime/
Takes a Date object, which I don't find really useful (a moment.duration would be more suitable, or an amount in millis, but I get how this is moment-agnostic) but props `min` and `max` used that too so I figured I'd use the same method :)

Added scrollTime prop like in FullCalendar

---

src/Month.jsx

cc @jquense 
In the _Show X More_ popup, it was trying to pull `eventComponent` from props but that was never passed in.  Lets make sure it gets passed in.

allow a custom popup component and use the right event component in default popup

---

src/Agenda.jsx

e.g.
'start': new Date(2015, 3, 7, 13, 15),
'end': new Date(2015, 3, 10, 17, 30)
shows 
<< 1:15 pm  // time from start date
instead of 
<< 17:30 pm

fix - wrong end time label in agenda

---

src/TimeGrid.jsx
src/less/time-column.less
src/less/time-grid.less
src/less/variables.less

In the week and day view a horizontal line represents the current time.
Apple Calendar and other apps use this concept to provide the current
time as a subtle hint.
The Y position of line is calculated in the TimeGrid by using a date
diff between this.props.max and this.props.min, respectively the
diff between current date and this.props.min.
To convert the result to a pixel value, the height of the time gutter
is used as a reference.
The position of the time indicator is calulated and updated every
minute using setInterval().
Please let me know if you want this feature to be toggled using a
prop.

Add an indicator that represents the current time

---

src/TimeGrid.jsx

The 'selected' prop was not being passed through to the header Event Rows for All Day events in Month/Week views, which meant that any logic which relied on that prop (special styling for selected events, etc.) wouldn't work. Fix is easy: just make sure to pass that prop down.

Pass 'selected' prop through to All Day Events

---

src/Month.jsx

Issue: One popup per row [per week] was being rendered
Solution: Moved _renderOverlay from renderWeek() to render(), also added check for this.state.overlay
This resolves the issue of popup closing on clicking inside the popup [or selecting any event]

Bugfix: Multiple showmore popups are being rendered

---

src/BackgroundCells.jsx
src/Month.jsx
src/TimeGrid.jsx
src/utils/selection.js

When trying to select a range of days ( when in Months view ) and using a RTL language (such as Hebrew) you'll find it buggy. It'll select the opposite days when in the current row and will do some weird stuff when passing between rows. I could not find any open issues or pull requests regarding that matter, so I decided to do it myself. I also added some documentation to the code to help me better understand it while finding a solution (I can take it down if it's a problem).
TL;DR
- The problem: Wrong selection indexes when using RTL language.
- Ways to reproduce the bug: Use the i18n example. Edit cultures.js by adding the **selectable** prop. Run it and select ar-AE.
p.s
This is my first time creating a pull request.

Days selection fix when using RTL languages

---

src/Calendar.jsx
src/DayColumn.jsx
src/EventCell.jsx

I created #215 and figured I'd submit a preliminary PR to see what you guys thought. It doesn't seem to be a huge change and would provide some interesting capabilities to users if they wanted. Currently on some of the views the arguments I am getting are 
`[event, SyntheticEvent, null, SyntheticEvent]` instead of `[event, SyntheticEvent]`
If this is something you guys are interested in, I can dig a bit more and find the source of that. I also think it might be interesting to provide this same capability to `onSelectSlot`, but I think that would be a bit more difficult given the dragging and my current use case doesn't require it.
Thoughts?

Included SyntheticEvent object in callback for onSelect in EventCell

---

src/BackgroundCells.jsx

BackgroundCells PropTypes - allow `selectable` to take 'ignoreEvents'

---

src/less/time-grid.less

time-grid.less has a dangling child selector (`.rbc-row > {`) which is technically illegal less syntax. The normal js-based less compiler everyone uses will ignore the child selector and emit css anyway, but alternative less compilers (like the java-based less4j) have stricter syntax requirements and error-out when they encounter this construct.
Patch removes the dangling child selector.

Remove invalid less selector for less4j

---

src/addons/dragAndDrop/backgroundWrapper.js

Before (you can see the bug here http://intljusticemission.github.io/react-big-calendar/examples/index.html#api ):
- if you move the 7am event to a different date cell, the time will be reset to 0am
After:
- when moving events to a date cell wrapper, time will be preserved (date will be changed, but time will still be 7am)
This PR fully fixes it.

Fix dnd date merge when moving an event to a date cell

---

src/BackgroundCells.js
src/Calendar.js
src/DayColumn.js
src/Month.js
src/TimeGrid.js

An `action` of `'click'` or `'select'` is now included in the object passed to the `onSelectSlot` callback.
Addresses #323 -- I tried to touch as little code as possible

Pass mouse event action to onSelectSlot() callback

---

src/addons/dragAndDrop/index.js

Hello everybody,
this pull request is for this issue https://github.com/intljusticemission/react-big-calendar/issues/350 , where once you have multiple HTML5Backend or Touch backends in your app, you can't use your app properly as you can't have 2 or more HTML5Backends at once.
This restriction about HTML5backend is documented, but it is not solved very well yet (https://github.com/react-dnd/react-dnd/issues/186). 
This pull request solves it by providing an option to choose if you want to use RBC with DragAndDrop context or you will provide your context in higher order component => you can use it like this: 
`const DragAndDropCalendar = withDragAndDrop(BigCalendar, { withDnDContext: false });`. 
This request does not contain any breaking changes.
I hope this will be useful for anyone …

Use withDragAndDrop addon without DnDContext

---

package.json

React v15.5 deprecates using `React.PropTypes` and instead you must import from `prop-types`. Also, `React.createClass` is deprecated and will be removed in version 16. 
This library has a dependency on react-overlays, which only fixes these issues in `0.7.0`. This PR allows for this new update to avoid these warnings/errors when using React Big Calendar.

Updated react-overlays to ^0.7.0.

---

src/EventRowMixin.js

- #384 - Warning on Event Click
- Updated PropTypes declaration of selected in EventRowMixin as well as the default propType of selected to be an object

#384 Resolve PropTypes Warning on Event Click

---

src/Calendar.js

docs(Calendar): document `selected` (and `defaultSelected`) props

---

src/DateContentRow.js
src/utils/eventLevels.js

I'm trying to make month view that has a filtered range (imagine defining visibleWeekDays=[1, 2, 3, 4, 5] to render all days except saturdays/sundays, or to have a shouldDayRender function that returns true/false depending on the date). These filters apply to the range that is handed to `<DateContentRow />`. 
Unfortunately, this doesn't currently work since the event padding is calculated via the difference between range start and event start. With this PR, we would get the correct padding without assuming that all dates are shown.
This is how a use-case this PR allows could look like:
Its simply a custom month-view rendered 4 times, that squeezes all days in one row and filters out saturdays/sundays.

Calculate segment padding according to actually visible dates

---

src/utils/propTypes.js

When passing object to `views` property, there is an error in browser: 
```
Warning: Failed prop type: validator.apply is not a function
```
The reason is incorrect usage of [react-prop-types#all](https://github.com/react-bootstrap/react-prop-types#allvalidators), which spreads args, but does not handle arrays.
Component itself continues to work fine though.

Fix prop types validation when passing object to views

---

src/Calendar.js
src/TimeColumn.js
src/TimeSlot.js
src/TimeSlotGroup.js

slotPropGetter - Allow to style cells

---

src/Popup.js

Prevent popup growing up outside of calendar. Before this change, the logic is when overlay reaches bottom it will grow up.
If there are too many events in a day, when the overlay reaches the bottom it can grow up outside calendar since the top can be a very big negative number. In this case I can't scroll to view hidden events.
After this change, the logic is when overlay reaches bottom it will grow up until it reaches the top of calendar, then it grows downward. So I can scroll down to view other events.

Prevent popup growing up outside of calendar

---

src/TimeColumn.js
src/TimeSlotGroup.js

#316
Uses the dateFormat propType from `utils/propTypes`, which matches the PropType for the timeGutterFormat in `Calendar.js`
Thanks for react-big-calendar!

Fix timeGutterFormat propTypes

---

src/BackgroundCells.js
src/Calendar.js
src/DateContentRow.js
src/DayColumn.js
src/Month.js
src/Selection.js
src/TimeGrid.js
src/less/month.less
src/less/styles.less
src/less/time-grid.less

This PR adds support for touch events when "selectable" is enabled. The
selection box appears after the user presses and holds on the screen
for 250ms as to not interfere with scrolling. This is similar to how the native iOS calendar behaves.
I ended up reorganizing/renaming some things in `Selectable.js` to make things make more sense in the context that it is not necessarily _mouse_ events that are being handled.
I'm looking forward to your feedback on this, and am happy to make any changes you suggest! Cheers!
Fixes #38.

Add support for "selectable" calendar on mobile

---

examples/demos/basic.js
examples/events.js
src/Calendar.js
src/DayColumn.js
src/TimeGrid.js
src/Toolbar.js
src/formats.js
src/less/event.less
src/localizers/globalize.js
src/localizers/moment.js
src/localizers/oldGlobalize.js
src/utils/dayViewLayout.js

Added the config option `showMultiDayTimes` to show multi-day events with defined start and end times to show in the time slot views as opposed to the all-day header.
However there were limitations in doing this as all day events and time range events are rendered as separate objects, so when there is an 'in-between' day in the multi-day event, this will take up the entire time slot view for the given days. I found this to be more desirable, because if it were that way, then clicking on the all day object would not link to the rest of the days in the event.
The bulk of this work is from PR #42 but I have updated it with the new styling changes from the past year, as well as made this feature a configurable option.

Option to show multi-day events with specific start and end times in time-slots

---

src/Agenda.js

Currently, the eventPropGetter is not used at all for the agenda view, which means the event nodes in the agenda view cannot be customized through this prop. This PR fixes that and also adds semi-colons to all the lines that are missing them in the agenda view.

Use event prop getter in agenda view

---

src/EventCell.js

Correct calculation of .rbc-event-continues-after class

---

src/DateContentRow.js
src/Month.js

Default 'now' prop in Month view so that the .rbc-now class is correctly added to the current date when the 'now' prop isn't supplied to the Calendar.

Fix for marking date as 'now'

---

package.json
src/utils/eventLevels.js

Please consider adding these two fixes for making React Big Calendar work again in Internet Explorer 11, since both of these functions are unsupported and need Polyfills.

Fixing #464 and #467 for IE11 Compatibility

---

src/Calendar.js
src/DayColumn.js
src/EventCell.js
src/EventRowMixin.js
src/Month.js
src/TimeGrid.js

This PR is part of #563 issue
New:
* `onDoubleClickEvent` handler
Callback fired when a calendar event is clicked twice.
`(event: Object, e: SyntheticEvent) => any`
All changes are similar to `onSelectEvent` handler

Add event doubleClick handler

---

src/Calendar.js

The documentation is showing the wrong information for `agendaHeaderFormat` -- it is `dateRangeFormat` not `dateFormat`. I tracked it down to it being set wrong in `src/Calendar.js`.

fix agendaHeaderFormat in Calendar

---

examples/demos/selectable.js
src/BackgroundCells.js
src/Calendar.js
src/DayColumn.js
src/Selection.js

This PR is a part of #563 issue
Selection object already has support for slot selection with `action: 'click'` property passed to `onSelectSlot`. We have to add support for double click interaction, with `action: 'doubleClick'` property passed.
Now Selection object emits `click` event on every click, so if you click twice, it will emit 2 `click` events with a small delay.
To emit `doubleClick` event inside `Selection` object, we have to check, wether first click is just a single click (then we emit `click` event), or it's the first click of double click (then we should mute it):
1. User makes the first click. Don't emit `click` event yet. Create a timeout for 200ms (usual max delay between 2 clicks of double click). Remeber timestamp of the first click.
2. User makes the second click. …

Add doubleClick support to slot selection

---

.storybook/config.js
.storybook/webpack.config.js
package.json
stories/Calendar.js
yarn.lock

In order to help profile performance issues that are blocking #423 , it is incredibly helpful to [upgrade storybook](https://github.com/storybooks/storybook/pull/623) so that you can use [`react_perf` url parameter](https://reactjs.org/blog/2016/11/16/react-v15.4.0.html#profiling-components-with-chrome-timeline)

Migrated to storybook3 with the necessary webpack config changes

---

src/Calendar.js
src/DayColumn.js
src/TimeColumn.js
src/TimeGrid.js
src/TimeSlot.js
src/TimeSlotGroup.js
src/addons/dragAndDrop/backgroundWrapper.js
src/less/time-grid.less
stories/Calendar.js
stories/resourceEvents.js

I've created this PR, that serve the same purpose as https://github.com/intljusticemission/react-big-calendar/pull/373. The difference is that the logic of the resource is done directly in the `TimeGrid` instead of creating a `ResourceGrid` which DRY things up and allow to enjoy resource in the week view as well.

Add resource

---

src/less/time-grid.less

There's currently a minor alignment issue with the borders in the week view (https://github.com/intljusticemission/react-big-calendar/issues/631). This fixes it for me (tested in latest chrome, safari and ff on mac), and I haven't seen any other problems with it. 
**Before:**
**After:**

fix border alignment issues

---

examples/Intro.md

Ran into the same issue as this person: #162
I think it would be clearer if the example used the same accessors as the intro page.

Use same convention as the example app

---

examples/Api.js
examples/App.js
examples/demos/basic.js
examples/demos/cultures.js
examples/demos/customHeader.js
examples/demos/customView.js
examples/demos/popup.js
examples/demos/rendering.js
examples/demos/selectable.js
examples/demos/timeslots.js

React 16 was introduced with https://github.com/intljusticemission/react-big-calendar/pull/671 , so we can't use `React.createClass` any more. This means neither stories or examples can be run at this point. I updated all the examples to use es6 instead, but (I think) the `markdown-jsx-loader` still uses `React.createClass`, so that package will also have to be updated before stories and examples work again.

use es6 instead of React.createClass for examples

---

src/less/event.less

After some recent changes, events became unselectable on weekly view if not using drag and drop.

fixed non selectable events on weekly view

---

src/Agenda.js
src/Calendar.js
src/DayColumn.js
src/EventCell.js
src/EventRowMixin.js
src/Month.js
src/TimeGrid.js

Use a "tooltipAccessor" prop for the tooltip instead of the "titleAccessor" prop. Can show a tooltip different from the title, or not display it at all if the accessor returns null.
Fixes #226, #470

Add tooltipAccessor prop to calendar to disable tooltip if needed

---

src/addons/dragAndDrop/styles.less

This PR is to fix the issue related to not being able to drop an event onto itself when resizing an event to be smaller than its current length. I removed the related styling that was preventing this and the app now works as expected.
<a href="https://cl.ly/3Z3c0I0N1225" target="_blank"><img src="https://dha4w82d62smt.cloudfront.net/items/3f3G0G400x2T3n2V3f3s/Screen%20Recording%202018-02-12%20at%2010.46%20AM.gif" style="display: block;height: auto;width: 100%;"/></a>
#656

Fix dnd style preventing event from dropping on itself

---

src/TimeGrid.js

Remove 'resize' event listener on TimeGrid unmount

---

src/BackgroundCells.js
src/Calendar.js
src/DayColumn.js

I want to render an in-line popup at the `{x,y}` coordinates of the selection event, so passing back the `box` (for clicks) and the `bounds` (for select) makes this possible.

Add box and bound to onSelectSlot callback

---

src/DayColumn.js

This causes a many unnecessary `render()` of `DayColumn` calls, which leads to high CPU usage on IE11.

Don't call setState too often on selection

---

examples/events.js
src/TimeGrid.js
src/less/time-grid.less

Update time indicator to only show the bar on the current day instead of the full week.
This behavior is more consistent with gcal and is less confusing when looking at the calendar

Update display of time indicator

---

src/BackgroundCells.js

I think I missed this in my first PR, so some click events are not passing through the `box` properly

Add box arg to _selectSlot on BackgroundCells.js

---

README.md

This PR adds a set of starter repositories to the README for those needing help with a local setup.

Add starters to README to help with local setup

---

src/utils/TimeSlots.js
test/utils/TimeSlots.test.js

I was about to make an issue, but figured I could create a pull request instead.
The issue I was about to post:
> #### Do you want to request a _feature_ or report a _bug_?
> Bug
> 
> #### What's the current behavior?
> The new TimeSlots metrics generate the wrong number of timeslots, so the last timeslot is not included (the one that goes to 23:59), making it unselectable. You can see it here:
> 
> - [CodeSandbox](https://codesandbox.io/s/13kqjp5o43)
> - http://g.recordit.co/Sy5qUDTpya.gif
> 
> I've also tested this with any given `min` and `max` value, the same happens, so it isn't just 23:59 timeslot that is excluded. 
> 
> #### What's the expected behavior?
> The last timeslot in any given day should be selectable.
This change should fix this issue. I've tested it with multiple …

Fixing TimeSlots getSlotMetrics

---

examples/demos/customView.js
examples/demos/dnd.js
examples/demos/rendering.js
examples/demos/resource.js
examples/demos/selectable.js
examples/demos/timeslots.js
src/addons/dragAndDrop/DropWrappers.js
src/addons/dragAndDrop/withDragAndDrop.js
stories/Calendar.js
stories/customComponents.js

When testing out the dnd addon I found this note in a comment in `withDragAndDrop.js`: 
```
* Note: you cannot use custom `EventWrapper`, `DayWrapper` or `DateCellWrapper`
* components when using this HOC as they are overwritten here.
```
This was a huge bummer for us because we are wanting to use custom `DayWrapper` or `DateCellWrapper` components for contextual styling on day and date cells while also using drag and drop. 
With this PR I took a stab at adding support for custom `DayWrapper` and `DateCellWrapper` components. I reviewed the discussion on #716 (initial implementation) to make sure I wasn't missing why this wouldn't be possible. 
- `DropWrapper` now receives the `components` prop. It will still use the default `BackgroundWrapper` if no custom `dayWrapper` or …

DnD support for custom DropWrapper components (dayWrapper and dateCellWrapper)

---

src/Selection.js

Fixes #630 #614 
The issue can be reproduced in Google Chrome on Windows (but not on macOS).
In this browser, mouseMove event is called after mouseDown without moving mouse cursor.
So this fixes not to emit SelectEvent until cursor moved from initial position.

fix selecting events in chrome

---

examples/demos/customView.js
src/Calendar.js
src/TimeGrid.js
src/TimeGridHeader.js
stories/Calendar.js

Hi
This change adds a new component option that gets inserted as the contents of the header of the time gutter in week and day views.
Closes #853
Added an example of using the component to "Custom View" in examples:

Add timeGutterHeaderComponent

---

src/Month.js

I have made [jalali version of this component](https://github.com/fingerpich/jalali-react-big-calendar) and I have this problem to make it rtl.

Fix rtl prop has to be passed to the DateContentRow

---

src/DayColumn.js
src/utils/DayEventLayout.js
test/utils/DayEventLayout.test.js

Fix for issues #886 and #909. The computed `minimumStartDifference` corresponds to a half section, when using the default CSS of 40px minimum height for a section and 20px minimum height for an event.

fix minimum start difference for same row computation (#886) (#909)

---

src/Calendar.js
src/TimeGrid.js
src/TimeGutter.js
stories/Calendar.js
stories/helpers/customComponents.js

Expose timeSlotWrapper so a custom timeSlotWrapper can be passed through! 😃

Add custom timeSlotWrapper support

---

src/TimeGridEvent.js

Currently, event clicks can't be clicked on the master branch, because the onClick event is passed on a react component (**NoopWrapper**) and not a Dom element
https://github.com/intljusticemission/react-big-calendar/blob/master/src/DayColumn.js#L198
This PR propagates the onClick and onDoubleClick to the containing div element, so that clicks on events work again.

This fixes event clicks/double clicks

---

src/EventCell.js
src/less/event.less
src/less/reset.less
src/less/variables.less

Switching EventWrapper content into `<button>` for accessibility purposes (navigation by tab).

Adding tabbable events

---

src/Calendar.js

Fixes #1042, the error isn't present on the examples until you add an `onRangeChange` prop. All that was required was passing the localizer through.

Fix onRangeChange not passing localizer

---

src/addons/dragAndDrop/EventWrapper.js

The reference to the draggableAccessor/resizableAccessor was incorrect. This PR fixes that.
#1068

Fix reference to draggable/resizable Accessor

---

examples/App.js

Previously sending someone to the example link like: https://intljusticemission.github.io/react-big-calendar/examples/index.html#cultures would not completely load the interface. (The culture drop down wasn't present until after menu selection)
I've moved the hash detection to componentDidMount() and used a set state to ensure we trigger a re-render.
To test select a non-default example and reload the page. Opening the menu and selecting the same value again should not cause any re-renders.

fix: Examples not fully shown until first state change

---

src/addons/dragAndDrop/EventWrapper.js

Drag and Drop was disabled if resizing is not allowed. This PR should take into account both isDraggable and isResizable when evaluating.
#1072

Fix dragging is disabled if resizing is not allowed

---

src/TimeGridHeader.js
src/less/time-column.less
src/less/time-grid.less

I don't see any reason why that should be hidden with javascript.
That causes an issue in our project, and I think we should let people decide wether they want to hide that or not (with CSS preferably)

No longer hiding the header when we only show one day

---

src/addons/dragAndDrop/withDragAndDrop.js

If the state is checked in the handleInteractionStart method, subsequent calls of setState are prevented. This leads to faster initializations of the dragging animation.

Increase startup time of event dragging

---

src/utils/TimeSlots.js

Fixes #999, #1051
Calendar shows integer number of timeslot groups, therefore even if `max` prop is set to 23:00, it will still render area with 00:00 as highest border.

Fix elements position on TimeGrid if max prop is set

---

.storybook/webpack.config.js

As I couldn't run Storybook, I made a workaround.

Remove extractText plugin to fix storybook

---

src/Calendar.js

Hi,
Added additional argument `view` for cases when `onRangeChange` called right after `handleViewChange` will be called. This guarantees to us to receive fresh `view` with fresh dates.

onRangeChange: new argument

---

src/Selection.js

Hello!
We were seeing an issue on IE11 while using the drag 'n drop functionality.
Every time I was done selecting some events / slots IE10 crashed on me.
I couldn't investigate much further, but it seems that `_handleMoveEvent` was called after `_handleTerminatingEvent`. This means that while trying to destructure `x` and `y` from this line `let { x, y } = this._initialEventData` that `this._initialEventData` was already set to `null`.
This is currently not a clean solution, but it works for our needs so far.
I am not 100% sure what the root cause is (why `_handleMoveEvent` is called again after terminating).

Fix: do not handle move event after terminating

---

src/Calendar.js
src/TimeSlotGroup.js

This tiny change enables users of this library to add custom slot classes depending on the slot resource & time.
I think that this is the most flexible solution for visually supporting things like business hours, breaks, times designated to specific types of events and so on.

Pass resourceId to slotPropGetter

---

src/addons/dragAndDrop/withDragAndDrop.js

There are many onMouseUp listeners (expecially in week view) , all calling this function, causing many `setState` calls. In particular, those calls do happen when you click an event to select it, severely delaying the feedback from the click.
I assumed if `state.action` is null, then the setState call is redundant, not sure if anything relies on this handler always causing a render or not. I tested for my use case and it works well. Reacting to a simple `onClick` on an event is now ~10x faster.

fix: short-circuit handleInteractionEnd when no action is in progress

---

src/DayColumn.js

fix: make sure time indicator is updated after navigation

---

src/Calendar.js

When view changed and props `date === undefined` we have unexpected behavior for `handleRangeChange` and then for `onRangeChange` methods. It returns sometimes `undefined` and sometimes `Invalid Date`, so I suggest fix for this to provide default date if `date` prop isn't present.
@jquense

Added fallback to getNow in `handleViewChange`

---

package.json

[TimeGrid](https://github.com/intljusticemission/react-big-calendar/blob/master/src/TimeGrid.js#L68) relies on `React.createRef`, which was added in React v16.3.

Bump react peer dependency to 16.3

---

src/TimeGrid.js

Reproduce the original issue (in Chrome):
1. Directly go to http://intljusticemission.github.io/react-big-calendar/examples/index.html#selectable
2. Notice that you cannot see the day headers because the width of the gutter is set way too big
By wrapping it in the requestAnimationFrame it ensures that it is set after the initial paint is finished (which does the css etc).

Fixed issue with gutter width initialization

---

.babelrc
.size-snapshot.json
package.json
src/Agenda.js
src/BackgroundCells.js
src/Calendar.js
src/DateContentRow.js
src/Day.js
src/DayColumn.js
src/EventCell.js
src/EventEndingRow.js
src/EventRow.js
src/Month.js
src/Popup.js
src/TimeGrid.js
src/TimeGridHeader.js
src/TimeGutter.js
src/TimeSlotGroup.js
src/Toolbar.js
src/Week.js
src/WorkWeek.js
yarn.lock

Remove propTypes in production

---

.size-snapshot.json
package.json
rollup.config.js

In this diff I added esm bundle which will allow user bundlers
to produce much smaller code. Currently regular babel output is
wrapped with module iife.
This project has a lot of files so with single esm file users will
bundle it slightly faster.
As a bonus we see the size of the project without dependencies.

Provide esm support for bundlers

---

src/Calendar.js

I've replaced `this._showMore` by callback from props. Seems it was added by mistake [here](https://github.com/intljusticemission/react-big-calendar/blob/f9a873368a78f5ced81b799c4dffe1095b3ab712/src/Calendar.jsx#L280), `_showMore` is always undefined.
Here it will be execute:
https://github.com/intljusticemission/react-big-calendar/blob/1d62c432eaa183ed6b38f08cfcec5ee7edcbfe41/src/Month.js#L300-L307
Related to #1147

Able to override onShowMore callback

---

src/Selection.js

This is a bug.
It was introduced in #884
on longpress range and therefore start and end variables were empty.
Fixed this by checking, whether the event is a Click.

fix selecting events in mobile browsers

---

src/Month.js

Pass the 'bounds' and 'box' props on slot select in Month view to the handler

Adding missing props on slot select in Month view

---

src/DayColumn.js

Hello,
It looked like PR for this issue (#1054) was abandoned and the bug still exists so I've decided to continue jdaberkow's work.
Also I've added check for `getNow` prop, because when you want to implement timezones you may have different `getNow` function depending on which timezone is selected. When user changes the timezone indicator should move to correct position for that timezone.

Fix misplacement of current time indicator

---

.babelrc

`.babelrc` is meant to be in JSON format, which requires double quoting key values and strings, and does not allow for trailing commas for the last item of lists or maps.

Make .babelrc be valid JSON

---

examples/events.js
src/Agenda.js

Some events may have the same start/end date/time, and are meant to represent point-in-time events, such as deadlines. These are not all day events, but they also should not be represented as `${startTime} - ${endTime}` since the values will be the same.
This will cause an event that is not marked as all day, and where the start and end are equal, to show as:
```js
// old
`${startTime} — ${endTime}` // 5:04 pm — 5:04 pm
// new
`${startTime}` // 5:04 pm
```

Support point-in-time events in the Agenda view

---

src/Month.js

I wanted to make a transition to date elements when they were selected, releasing that a couldn't get the `transition` property working. 
After some digging to my code and react-big-calendar code, I found that after selecting a date `DateContentRow` un&mount  their children components.
This happens due to the call of [this](https://github.com/intljusticemission/react-big-calendar/blob/master/src/DateContentRow.js#L121) `renderDummy` happens after setting `needLimitMeasure` to true in `Month.jsx` after the date is changed.
----------------------------
Prevent re-mount of DateContentRow children when date change in the same month
* Prevent setting `needLimitMeasure` to true when the month of the date is not changed,
in order to prevent unmounting and mounting of all the weeks' components.
* …

Fix: prevent un/mounting of date components

---

src/less/month.less

`whitespace: nowrap` already exists in rbc-ellipsis

remove duplicate style

---

examples/App.js
examples/demos/dndOutsideSource.js
src/Selection.js
src/addons/dragAndDrop/EventContainerWrapper.js
src/addons/dragAndDrop/WeekWrapper.js
src/addons/dragAndDrop/withDragAndDrop.js

This PR is meant to resolve issue #1090.
The change exposes the `onDropFromOutside` prop on the withDragAndDrop HOC, which takes a callback that fires when an outside draggable item is dropped onto the calendar. The callback receives as a parameter an object with start and end properties that are times based on the drop position and slot size. 
It is worth noting that it is entirely up to the user to handle actual event creation based on the callback. All that this API does is allow `draggable` DOM elements to trigger a callback that receives start and end times for the slot an item was dropped on, and a boolean as to whether it's an all-day event. If the user wants to know which event was dropped, they will have to handle that themselves outside of React-Big-Calendar. An example added to …

Provide onDropFromOutside prop for Dnd Cal

---

src/Agenda.js
src/Calendar.js
src/Month.js
src/Popup.js
src/TimeGrid.js

I am using react-big-calendar in an environment where we are forced to use multiple react versions (namely `15.6.2` and `16.7.0`) on the same page. react-big-calendar doesn't work in that environment as it sometimes uses the legacy [string refs](https://reactjs.org/docs/refs-and-the-dom.html#legacy-api-string-refs). This PR fixes this by using the [`React.createRef()`](https://reactjs.org/docs/refs-and-the-dom.html#creating-refs)-pattern. 
Additional info:
- The string refs pattern is deprecated due to several reasons (incl. performance) according to the [react team](https://github.com/facebook/react/pull/8333#issuecomment-271648615)
- Most probably this would also fix #968
- I tested using my application as well as by running the examples

fix: use React.createRef instead of string refs

---

src/DayColumn.js

When changing the `min` prop, the current time indicator is not re-positioned and therefore shows at the wrong place.
demonstration: https://codesandbox.io/s/y241x9njq1

fix: update time indicator position if min prop changes

---

src/addons/dragAndDrop/withDragAndDrop.js

This is really minor. 
The comment had me confused for a while until I figured out react-dnd is no longer used on this project.

docs(dnd): remove deprecated comment about `react-dnd`

---

.size-snapshot.json
src/Calendar.js
src/utils/propTypes.js

- replaced elementType with builtin one
- removed unused custom prop type

 Clean up prop-types

---

.size-snapshot.json
package.json
src/utils/propTypes.js

I found `all(object, customHandler)` can be replaced with
`objectOf(customHandler)` so we may drop prop-types-extra package.
There is still usage in react-overlays. Gonna send a PR too.

Remove prop-types-extra

---

.size-snapshot.json
src/Popup.js

`Element` does not exist in react. But it exists in prop-types.

fix: bad propType.

---

.size-snapshot.json
README.md
src/index.js

```js
import {
Calendar,
DateLocalizer,
momentLocalizer,
globalizeLocalizer,
move,
Views,
Navigate,
components
} from 'react-big-calendar';
```

feat: provide named exports api

---

.size-snapshot.json
package.json
src/Agenda.js
src/BackgroundCells.js
src/DateContentRow.js
src/Day.js
src/DayColumn.js
src/EventCell.js
src/Month.js
src/Popup.js
src/TimeGrid.js
src/TimeGridHeader.js
src/Week.js
src/localizers/globalize.js
src/localizers/moment.js
src/localizers/oldGlobalize.js
src/utils/DateSlotMetrics.js
src/utils/TimeSlots.js
src/utils/dates.js
src/utils/eventLevels.js
yarn.lock

The diff is quite nice.
```diff
-    "minified": 150810,
+    "minified": 148190,
-    "gzipped": 45487
+    "gzipped": 44792
```

chore(deps): upgrade date-math

---

src/Calendar.js
src/DayColumn.js
src/TimeGrid.js
src/TimeGridEvent.js
src/less/time-column.less
src/sass/time-column.scss

During some previous refactoring rtl was on some places renamed to `isRtl` or forgotten to propagate, causing it to not work at all - css was ignored.
I've reverted back to `rtl` notation as it common word already used in styles and in documentation as well.

fix: rtl incorrectly named or not propagated

---

src/addons/dragAndDrop/EventContainerWrapper.js
src/utils/TimeSlots.js

Tries to fix issue #1105.
Added options to ignore timeslot start or end so day is not cut to the end of current day during DnD move.
Used only in DnD handleMove - rest remains as before.
Only end date is ignored - tested, worked ok. 
When start date was ignored it causes some issues slot not being rendered in correct slot sometimes.
Wasn't sure about names, so feel free to comment :)

fix(addons): do not cut end while dragging multiday event

---

examples/demos/dndOutsideSource.js
src/Selection.js
src/addons/dragAndDrop/EventContainerWrapper.js
src/addons/dragAndDrop/WeekWrapper.js
src/addons/dragAndDrop/withDragAndDrop.js

While dragging over a cell it might be useful to see placeholder for an item where it will be inserted as soon we drop it.
**Please see example below**

feat(dnd): add preview of an item inside cell while dragging

---

package.json
yarn.lock

Increased date-arithmetic lib version with fixed bug which causes issue with month range calculation.
I also moved bootstrap-sass to dev-dependencies, as discussed in #1313 as it's only used in examples.

Fix: use fixed date arithmetic lib and move bt-sass to devdependecies

---

src/DayColumn.js

The fix in https://github.com/intljusticemission/react-big-calendar/pull/1311 only addressed the case of `min` changing, not the case of `max` changing.
This addresses the same thing as https://github.com/intljusticemission/react-big-calendar/pull/1297 but rebased on top of the changes from #1311
Demonstration: https://codesandbox.io/s/react-big-calendar-bug-5bmvb
@jquense @sonnyp

Update time indicator position if max prop changes

---

src/addons/dragAndDrop/WeekWrapper.js

This is same fix as already done for day and week views done in #1119 done for month view.
* Fix dropping an event out of month view bounds leaving the calendar in an intermediate state (no listener on reset)

Fix drag cancelation for month view

---

src/DayColumn.js
src/utils/TimeSlots.js

The function used to set the current time indicator (getRange) was changed in #1204 to fix #1203 but it broke the top position of the current time indicator as in #1396 
I have made a new function (getCurrentTimeIndicatorRange) that does almost the same as (getRange) but it is specific to current time indicator so there will be no conflict between how events are displayed and how time indicator is displayed.

fix: add new method to get correct time indicator top position | fixes #1396

---

src/utils/TimeSlots.js

Selection works correctly though visually there were two slots selected. I'm not sure what this logic was resposible for but it affected only end slot because of smaller range (30-59min) instead of 30-00.

Fix end slot selection

---

src/Calendar.js
src/DayColumn.js

I've added `resourceId` to onSelecting callback since without its impossible to detect which column is selecting when we have resources.

Add resourceId to onSelecting callback

---

README.md

Make the examples more clear in the readme file that the height is required in order for things to render correctly.

Add height style to README

---

.eslintrc
package.json
src/Calendar.js
src/localizers/globalize.js

Maintainers of `warning` refuse evolution saying it's a 1:1 fork of
fbjs version. I tend to replace it with just console statements wrapped
in NODE_ENV check. Looks much simpler to me, does not require
additional tools like babel plugin and does not require commonjs module.

Drop warning

---

.github/workflows/release.yml
.github/workflows/test.yml

Improve the releasing setup 
---
Addresses issue #1519
Tools used: [Github Actions](https://help.github.com/en/github/automating-your-workflow-with-github-actions/about-github-actions) |  [Semantic Release](https://github.com/semantic-release/semantic-release)
This PR introduces 2 workflows
1. Tests Workflow: Runs in every PR and ensures that tests & linting are passing 
- This flow is been tested here ✅[more details](https://github.com/KhaledMohamedP/react-big-calendar/commit/60b9478d75bf84e599bb44833ee8d0953a1741c8/checks?check_suite_id=293604078)
2. Release Workflow: Runs when anything gets pushed to master
- Releasing involve pushing to npm registry and adding a release tag
- This flow has not been fully tested, due to missing npm/github tokens ❌[more …

chore(github-actions): add semantic release and test workflow

---

src/BackgroundCells.js
src/Calendar.js
src/DayColumn.js
src/Month.js
src/TimeGrid.js
src/TimeGutter.js

There hasn't been any movement on #1515 or #1560 lately, so I thought I'd open this simple fix.
This PR prefixes all deprecated React lifecycle methods with the `UNSAFE_` keyword. In the long term these lifecycle methods should be refactored out, but in the interim there is no reason we need to continue to see the console full of warnings. 
For more context:
https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

Prefix all deprecated React lifecycle methods with UNSAFE

---

.size-snapshot.json
src/Calendar.js
src/TimeGrid.js
src/TimeGutter.js
src/TimeSlotGroup.js

Added a slotGroupPropGetter property to allow for custom styles to be passed to time slot groups. Useful for dynamic calendar sizing.

feat: Slot group prop getter (#1471)

---

package.json
src/utils/DateSlotMetrics.js
yarn.lock

The memoize-one team updated the isEqual API in version 5.0.0: https://github.com/alexreardon/memoize-one/releases/tag/v5.0.0
I'm taking that dependency bump and migrating the usage of isEqual here.

bump memoize-one and migrate new isEqual API

---

src/utils/TimeSlots.js
test/utils/TimeSlots.test.js

This small pull request fixes Issue #1442 
This issue occurs due to Pull Request #1204 
In the case where the range of an event is less than the step, this unmodified line will cause the position of the event to be positioned too early.
The bug, as demonstrated [here](https://codesandbox.io/s/react-big-calendar-issue-8mz4i)
When the `step` attribute is set to the minimum time, this fixes the issue, as seen [here](https://codesandbox.io/s/react-big-calendar-issue-i8vf9), but this forces a change in UI, which is not desirable.
While this current fix resolves the issue to correctly push any events past the calendar height back within, it has the unfortunate side effect of utilizing the `step` attribute to determine the height. For an arbitrarily large step, this will push it to the top of …

Fix for TimeSlots

---

src/addons/dragAndDrop/EventContainerWrapper.js

Fix an issue where dnd freezes an event intermittently

---

src/localizers/date-fns.js

Previous format string displayed a day as '13 013' when using date-fns, rather than '13 Fri' as
RBC would with the moment localizer.

Date-fns localizer - display dayFormat correctly

---

src/DayColumn.js

Fix addressing issue https://github.com/jquense/react-big-calendar/issues/1632.
Actually the fix should be reviewed cause even if it suits my needs, I am not sure it does not introduce a new bug.
The loop where the patch is located is in a function that notifies for a selected slot and contains the start, the end time and an array of times (slots), all Date objects. If one selects a slot from 0:00 to 3:15 (the day DST begins), the slot is
```
(10) […]
​0: Date Sun Mar 28 2021 00:00:00 GMT+0100 (Central European Standard Time)
​1: Date Sun Mar 28 2021 00:15:00 GMT+0100 (Central European Standard Time)
​2: Date Sun Mar 28 2021 00:30:00 GMT+0100 (Central European Standard Time)
​3: Date Sun Mar 28 2021 00:45:00 GMT+0100 (Central European Standard Time)
​4: Date Sun Mar 28 2021 01:00:00 …
```

Prevent endless loop when adding event the DST begin day

---

package.json

In response to [Issue 1651](https://github.com/jquense/react-big-calendar/issues/1651) in the original repo.

chore(vers): upgrade prop-types

---

examples/demos/dnd.js
src/Month.js
src/Popup.js

I've added in the ability to move events from the Popup in the Month view. Once the event has dropped onto the new day of the month, it will remove itself from the Popup and subsequently close that component.
I also added this into the `dnd` example to show the functionality.

Added dragging ability from the monthly Popup component

---

src/Calendar.js

The types declaration of onRangeChange function are wrong: onRangeChange function always returns also the view parameter (undefined when clicking on next/prev buttons but valued when changing view).
https://codesandbox.io/s/goofy-noether-6kgst
I've already asked for an update also on related typescript library here:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45358

fixed return type for View parameter

---

src/Calendar.js

The `step` property accepts minutes but this is not explicitly mentioned. Although the default value of `30` suggests that minutes should be given, this is not immediately obvious.

Documentation: clarify the time unit for 'step'

---

package.json

Reflect new repo location.
This also fixes the following linting error on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped):
```
Error: At least one of the project urls listed in the header, ["https://github.com/jquense/react-big-calendar"], must match the homepage listed by npm, 'https://github.com/intljusticemission/react-big-calendar'.
If your d.ts file is not for the npm package with URL https://github.com/intljusticemission/react-big-calendar,
change the name by adding -browser to the end and change the first line
of the Definitely Typed header to
// Type definitions for non-npm package react-big-calendar-browser
at check (/Users/sebu/Devel/_forks/DefinitelyTyped/node_modules/dts-critic/index.js:169:23)
at dtsCritic …
```

intljusticemission renamed to jquense

---

src/utils/TimeSlots.js

ref: #1646 
`rangeEndMin > step * (numSlots - 1)` will cause the event(`00:00 ~ 23:31(to 23:59)`) shift to wrong position.

Fix top part of 24hour event in week/day view

---

.size-snapshot.json
src/BackgroundCells.js
src/DateContentRow.js
src/TimeGrid.js

Apologies, I couldn't find any specs in regards to contributions format, etc. Happy to make changes/add additional info if I missed a guideline doc.
**Context for PR:**
Currently when using resources `onSelectSlot` returns the `resourceId` with the `slotInfo` when selecting within the `DayColumn`.  Unfortunately, when selecting within the `DateContentRow` (rendered by `TimeGridHeader`, the all day events area) it fails to return the `resourceId` with the `slotInfo`.
This PR aims to add that additional argument to the `slotInfo` in order to remain consistent and identify which resource is being selected when a user is clicking, dragging, dblclick within the all day area.
Again, happy to make changes or take guidance on a more preferred method of implementation (as well as format of PR …

adds resourceId to handleSelectAllDaySlot fns slotInfo

---

src/Calendar.js
src/DateContentRow.js
src/DayColumn.js
src/EventCell.js
src/EventRowMixin.js
src/Month.js
src/Popup.js
src/TimeGrid.js
src/TimeGridEvent.js
src/TimeGridHeader.js

This PR implements an onKeyPressEvent prop which can be passed to the Calendar.
The implementation works exactly the same as how the onDoubleClickEvent was implemented and this prop will provide functionality to pass a function which should fire when the focus is on an event and the user presses any key.
see #1753 for more context

Add onKeyPressEvent

---

src/sass/time-column.scss

I found a bug that shrinks the height of the TimeColumn when viewed in IE11.
Added `height: 100%;` as well as other parts, so that it won't collapse on IE11.
↓ Before
↓ After

Fixed a bug that the height of the column is broken when displayed in IE11

---

src/DateContentRow.js
src/DayColumn.js
src/EventCell.js
src/EventRowMixin.js
src/Month.js
src/TimeGrid.js
src/TimeGridHeader.js
src/addons/dragAndDrop/EventWrapper.js
src/addons/dragAndDrop/withDragAndDrop.js

Update the `resizable` prop to determine whether events
could be resized. Before, the prop could be supplied, but it
would not do anything.

Enforce `resizable` prop

---

src/addons/dragAndDrop/WeekWrapper.js

When an event is resized horizontally (e.g. on the Month
View), keep the time of the event the same and only change
the date.
This also fixes the bug where you cannot resize an event to
a single day because the `dates.max` or `dates.min` would
force the event to occur at least 1 day after the
`start` or `end` respectively.

Preserve time on horizontal resizing

---

src/addons/dragAndDrop/WeekWrapper.js

When an event is resized to span multiple rows, the preview
segments in the non-ending row would not be removed because
the `!pointInBox` would cause an early return.
This commit removes segments when the resize action finishes.
`onEventResize` is set to an empty function so we would expect the event to revert back to normal when the resize action ends.
**Bug**:
The preview segment in the 3rd and 4th rows persist after the resizing is finished.
**Updated**:
The preview segment in the 3rd and 4th rows are removed after resizing is finished. The event state is the same as the original state since `onEventResize` is an empty function.

Fix bug with resize segments not being removed

---

src/Calendar.js
src/DateContentRow.js
src/Month.js
src/ScrollableWeekWrapper.js
src/less/styles.less
src/sass/styles.scss

This prop will allow the rows in the `month` view to display
all events in a scrollable container, rather than use the
`show more` capability.

Add `showAllEvents` Calendar Prop

---

src/DateContentRow.js
src/DateHeader.js
src/Header.js
src/Month.js

While we're happy in general of being able to use this component for our work, the lack of accessibility has been quite the problem lately. This is not a full solution by _any_ means, but it can enable a screen-reader user to actually navigate through the table of events. Notice that this PR basically just adds roles and a few minor things; it should not crash anything!
One thing that I was unable to fix was the fact that the user is still unable to read the events per se; in our custom code we had to resort to move the focus once the situation was found from the front-end, but that's definitely no good!
Note: This mainly address the **Month** view. From what I've tested, the Week view will be basically invisible for the time being to screen-reader users!

feat: add accessibility to month view

---

README.md

Hello guys! 
I just discovered this library and I noticed this link was incorrect in the gh pages so the user gets a GitHub 404 page, please consider this pull request.

fix: update gh-pages readme to have the correct [demo and docs] link

---

package.json

I'm using the library in a react 17.x project and works perfectly, however the `npm install` shows the breaking dependency warning:
`npm WARN react-big-calendar@0.28.6 requires a peer of react@^16.6.1 but none is installed. You must install peer dependencies yourself.`
Also, using the paketo-buildpacks exits with error building the image:
`npm ERR! peer dep missing: react@^16.6.1, required by react-big-calendar@0.28.6`
Thanks for the help!

Update react & react-dom peer-dep to support 17.x

---

src/addons/dragAndDrop/WeekWrapper.js

https://github.com/jquense/react-big-calendar/issues/1886
Drag and drop is currently using the very left edge of the calendar as an offset from the mousedown position. 
Resulting in unusable behavior. 
`getSlotAtX` is being sent an `x` value of `point.x - point.x - bounds.left`
It appears with the last few merged commits that `eventOffsetLeft` is no longer needed and removing it fixes all issues.

Dnd: Offset is not needed

---

src/Month.js
src/TimeGrid.js

For end date in month-view slot-selection increase day by 1.
Fixes: #1909
EDIT:  The fix is applied for Month View, whole days Week view, whole day in Day view.

[Create event] fix end date on slot selection

---

.size-snapshot.json
src/Calendar.js
src/DayColumn.js
src/DayColumnWrapper.js

The idea is to have a props-providable component hook for the top-level element inside of `DayColumn`.
Let me know what you think and whether this can go forward.

Introduce DayColumnWrapper component hook

---

src/Calendar.js
src/Month.js

Setting popup={false} doesn't let you control the onShowMore function properly as described in #1147  and #1527 , because it only goes to the drill down view. In order to fix this, I've added another prop called `doShowMoreDrillDown` that is defaulted to `true`. If true, it will do the same thing it currently does, and go to the drill down view. However, if you set this prop to false, it will instead just trigger the `onShowMore` function where you can then show your own customized popup as desired.
Fixes #1147 
Fixes #1527

feat: Add new Calendar prop: `doShowMoreDrillDown`

---

src/Calendar.js

Just a couple of quick fixes for typos

Fix typos in prop descriptions

---

README.md

Avoids the "insecure" warning in some browsers. GitHub pages are HTTPS enabled and my (very quick) test suggests that the whole site works fine with https.

Use https for github pages link

---

src/utils/TimeSlots.js

s. https://github.com/jquense/react-big-calendar/issues/1685

fix: numGroups calculation

---

src/EventEndingRow.js

Since updating to React 17, the "show more" popup hasn't been working on a project I work on. This fix prevents the popup from closing immediately when being opened, by stopping the propagation of the click event on the "show more" text.

Avoid popups closing immediatly with React 17

---

README.md

Per date-fns/date-fns#2474, the `date-fns` example in the readme might've been wrong/broken. I am not familiar with your project, so please double-check that this suggestion is OK!

Improve the date-fns example in readme

---

src/utils/selection.js
test/utils/selection.test.js

I had noticed that, when using `react-big-calendar` I would pass the event that was selected, but the rendered component would not be selected (the `selected` prop was `false`).
Upon investigating, I found it to be an issue with the `isSelected` function. I wrote tests to confirm this.
Here is the output of the tests before the code change:
```
√:react-big-calendar rdbaker $ yarn test
yarn run v1.22.5
$ yarn lint && jest
$ eslint src test
Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .
PASS  test/utils/TimeSlots.test.js
PASS  test/utils/eventLevels.test.js (5.138s)
PASS  test/utils/DayEventLayout.test.js (5.265s)
FAIL  test/utils/selection.test.js
● isSelected › it returns true if it is the same …
```

Fixes the isSelected function to work if the value is equal

---

.github/workflows/release.yml
package.json
release.config.js

Updates to the Release GitHub Action to properly update the CHANGELOG and push release number updates to the package.json on release.

ci: Fix package and changelog updates on release

---

.size-snapshot.json
package.json

Since `./src` folder is not distributed with package install, we must reference the `./lib` folder for proper sourcemapping in the CSS file.
This resolves issue #2086

fix(sass): Reference distributed folder in SASS compile

---

src/addons/dragAndDrop/WeekWrapper.js

**Issue**:
When event end  time equals  0 am, end day (because end day equals previous day)  plus 1 day is a correct move.
however, when event time end time after 0 am, end day do not need plus 1 day any more.
**For Author or Administer**:
Please check my PR, THX

FIX_RESIZE_BUG

---

src/utils/layout-algorithms/no-overlap.js

Slight bug that prevents the stretch behavior of the no overlap algorithm from working properly
Without the fix:
With the fix:

fix: Correct no overlap algorithm stretch behavior

---

src/Calendar.js
src/Day.js
src/Month.js
src/TimeGrid.js
src/Week.js
src/WorkWeek.js

Feature
* Users should be able to disable auto-scroll which happens when calendar is rendered.
* By default we enable the auto-scroll, users have a mechanism to disable autoscroll.
* https://github.com/jquense/react-big-calendar/issues/1717

Add a functionality to disable auto-scroll on calendar render.

---

src/addons/dragAndDrop/EventContainerWrapper.js
src/utils/TimeSlots.js

Bug
* When users try to resize a multi-day event, the resize just changes the event start/end as per that day's start/end.
* Resizing a multi day event should change just the start or end of the event and the start/end across the other days should remain consistent.

fix: Correct resize for multi-day event.

---

src/DayColumn.js

* DayColumnWrapper is incredibly helpful component.
* slotMetrics is already exposed in EventContainerWrapper component and with this fix will be exposed to DayColumnWrapper component as well.

chore: Expose slotMetrics to DayColumnWrapper component

---

stories/guides/Dates.stories.mdx

docs: spelling error

---

.size-snapshot.json
babel.config.js

Fixes #2153 
Changes in e5721ef127d407a12ac74514981b311a1558fd2b seems to have enabled absolute runtime imports during builds for v0.39.4 which results in absolute paths to `@babel/runtime`. This can be verified by checking one of the built files: https://unpkg.com/react-big-calendar@0.39.4/lib/Calendar.js (see [v0.39.3](https://unpkg.com/react-big-calendar@0.39.3/lib/Calendar.js) for comparison)
This fixes the issue by setting `"absoluteRuntime": false` config option for `babel-preset-react-app`.

fix: disable `absoluteRuntime` in babel-preset-react-app

---

.scripts/build.mjs
.size-snapshot.json
babel.config.esm.js
babel.config.js
rollup.config.js
yarn.lock

Fixes #2156 
Fixes CJS/ESM build issues caused by react-app preset.
Since CRA's babel preset is being used, there's a bit of inconsistency causing build issues. This commit resolves that by passing `useESModules: true` as an option into `babel-preset-react-app`.
It also restores the `lodash-es` replacement present in 0.39.3 by keeping a separate babel config for ESM builds.
The package build corresponding to this PR can be tested by changing package.json dependency similar to the following:
```
{
"dependencies": {
"react-big-calendar": "git+https://github.com/sangeeth96/react-big-calendar#fix/babel-dist-lib-no-esm--dist"
}
}
```
and then running your app.

fix: incorrect babel imports in CJS/ESM builds

---

.size-snapshot.json
package.json

Possible fix for #2151 
This commit moves `react` and `react-dom` back into `devDependencies`.
`react` and `react-dom` needs to be in `devDependencies` to avoid issues arising from loading multiple react versions when RBC is installed. I was able to verify this happening by installing rbc 0.39.6 to a CRA project with `react@16.14.0`. In that case, both the project's version and the library's `17.x` version were installed causing issues running the project.
Additionally, supported react/react-dom/moment versions are also listed in `peerDependencies`.

fix: move react, react-dom to devDependencies

---

.husky/pre-commit
src/Calendar.js
stories/props/API.stories.mdx
stories/props/events.mdx
stories/props/events.stories.js

Changes to default props to no longer make
events required, defaulting to an empty array
#1708

feat(events): default events prop to an empty array

---

src/localizers/luxon.js

Currently there is an error while using luxon localizer with custom culture.
The issue is because of invocation of wrong luxon method.

fix: correct luxon localizer formatting

---

package.json

Added support for React v18.x.x

Added support for React v18.x.x

---

src/Selection.js

Fixes the issue #2147  when resizing an event past the root container, also solves drag creating an event that had the same issue.
You can observe the issues here:
[Resizable story](https://jquense.github.io/react-big-calendar/examples/index.html?path=/story/addons-drag-and-drop-props--resizable) - resizing event past the container causes the event to reset.
[Create events story](https://jquense.github.io/react-big-calendar/examples/index.html?path=/story/examples--example-2) - creating an event while dragging causes the event to reset

2147 Fixed resetting event when resize action was done outside of container

---

src/Selection.js
src/addons/dragAndDrop/WeekWrapper.js

Fixes #2198 issue.
Seen in https://jquense.github.io/react-big-calendar/examples/index.html?path=/story/addons-drag-and-drop--example-2 day/week views.

Fixes issue of loosing droppable event when releasing on non-event related containers

---

src/BackgroundCells.js
src/DateContentRow.js
src/DayColumn.js
src/DayColumnWrapper.js
src/Month.js
src/TimeGrid.js

This replaces all reference of `findDOMNode` with true ref notations, resolving core issue with #2193 .

fix: replace findDOMNode with refs

---

src/TimeGrid.js
src/TimeGutter.js

Correct issues with the TimeGutter ref

fix: correct TimeGutter ref

---

src/TimeGutter.js

Forgot to account for the DST offset fix in last commit

fix: adjust TimeGutter for DST

---

src/BackgroundCells.js
src/Calendar.js
src/DateContentRow.js
src/DayColumn.js
src/Month.js
src/TimeGrid.js
stories/props/scrollToTime.stories.js

This removes unsafe deprecated methods.

feat: replace unsafe deprecated methods

---

src/addons/dragAndDrop/EventWrapper.js

Use getAttribute('class') instead of className. className can be an object
as per web standards.
* This fixes a bug when there is className is a SVGAnimatedString inside the event card.
Web standards for className : https://developer.mozilla.org/en-US/docs/Web/API/Element/className#notes
* I have not added a story for this bug, as such it is outside the scope of this project. We are just adhering to the right standards.
* The existing story for DnD is functional with this bug including resize not triggering movement.

fix(dnd): dont use classname

---

.storybook/preview.js

The last comment in #2255 was about defaulting to "Docs" tab in storybook. 
This small change does just that.
Note that it doesn't work on the first page loaded (not an issue since "canvas" and "docs" are the same).
You may need to clear your browser's cache.

docs: make "Docs" tab default

---

src/TimeGrid.js

Bug fix: in scenarios where gutterRef is not defined specifically when using TimeGutterWrapper, we send null/undefined ref to getWidth function. getWidth function doesn't accept null/undefined argument. We already have a `?` check in the code just fixing it so it actually works.

fix: do not send undefined/null gutterRef to getWidth

---

.github/workflows/release.yml
.github/workflows/test.yml
src/Popup.js

ci: correct release

---

README.md
stories/AboutBigCalendar.stories.mdx

Remove the (mostly defunct) Discord links from documentation, replacing with link to invite to new Slack workspace.

docs: add slack invite links

---

src/localizers/luxon.js

Closes #2361
Round down the date difference returned in the `diff` function of the luxon localizer to the nearest whole number, aligning the behavior with other localizers.
For example, the `momentLocalizer`  uses the moment diff, which truncates the result to zero decimal places [by default](https://momentjscom.readthedocs.io/en/latest/moment/04-displaying/07-difference): 
https://github.com/jquense/react-big-calendar/blob/52a6d1f3d9ac047d9f1fcf2f2081a1c2f1749781/src/localizers/moment.js#L202
Before:
Now:

fix: rounding behavior in Luxon localizer

---

src/Calendar.js
src/TimeSlotGroup.js
stories/props/API.stories.mdx
stories/props/slotGroupPropGetter.mdx

Personally I use it to handle DST differently but also could be used to style group based on date.
Also based on the source code https://github.com/jquense/react-big-calendar/blob/ad8defa643692911fd0b00c71b70de94715140a9/src/Calendar.js#L916 something like that was supposed to be done

fix: pass dates to slotGroupPropGetter

---

src/Calendar.js

fix: correct treatment of boolean view in 'views'

---

stories/Calendar.stories.js
stories/DragAndDrop.stories.js
stories/Durations.stories.js
stories/Layout.stories.js
stories/Timeslots.stories.js

Add a decorator to stories to wrap the Calendar in a styled container

docs: add decorator to wrap story in container

---

src/BackgroundCells.js
src/Calendar.js
src/Day.js
src/EventEndingRow.js
src/Selection.js
src/TimeGrid.js
src/TimeGridHeader.js
src/Week.js
src/utils/DateSlotMetrics.js
stories/props/API.stories.mdx
stories/props/allDayMaxRows.mdx
stories/props/allDayMaxRows.stories.js
stories/resources/allDayEvents.js

* Addresses #2386 
* Currently react-big-calendar is not limiting the amount of events in the All day row displayed in Week and Day view, if this row grows it may also cover the events and prevent the user from seeing their normal events.
* Add support for displaying Show more text in TimeGrid views via allDayMaxRows prop.
* Prevent Background cells from capturing click on show more button.

feat(time-grid): allow consumer to set allDayMaxRows (#2386)

---

stories/props/onSelectSlot.mdx

Update the `onSelectSlot` documentation to include the `resourceId`

docs: add resourceId to onSelectSlot documentation

---

src/DateContentRow.js

Fix issue #2310 and #1801
**Issue:** 
https://drive.google.com/file/d/1kKL80YCJLrz6q0Y1GJeWzlwNgkccJ-OA/view
When dragging an event in the RTL month view calendar, the calendar gets confused and the event goes in the opposite direction, this also happens in the week view at the allDay section.
**Solution:**
I have forwarded the `rtl` params to the `WeekWrapper`.
This is a fix specifically for dragAndDrop and doesn't solve all of the RTL problems.

Fix bug - Dragging an event in the RTL month view calendar gets confused to the wrong side

---

stories/resources/events.js

Name change due to Itaewon Halloween disaster.

Modify events.js

---

src/addons/dragAndDrop/EventWrapper.js

Fix for error: cannot add property 'X', object is not extensible
Above console error appears when using the Resource Drag and Drop feature of react big calendar to move events.  I narrowed the issue down to this code in the addons/dragandDrop/EventWrapper.js:
let extendedEvent = this.props.event
Per the [linked discussion on Stack Overflow](https://stackoverflow.com/questions/55567386/react-cannot-add-property-x-object-is-not-extensible), it is not possible to modify this.props directly. The solution is to create a copy of the props using JSON.parse() and JSON.stringify()
Thus the modified code that I have gotten working without error is:
let extendedEvent = JSON.parse(JSON.stringify(this.props.event))

Fix dragAndDrop EventWrapper.js error: cannot add property 'X', object is not extensible

---

src/DayColumn.js

Adds `isBackgroundEvent` flag to 'event' objects passed to `onSelectEvent`

fix: add isBackgroundEvent to onSelectEvent event obj

---

stories/props/onSelectEvent.mdx

docs: update onSelectEvent prop story

---

src/EventEndingRow.js
stories/props/messages.mdx

Sometimes, we need to incorporate additional event information into texts that display more items. Therefore, we have added the input of event parameters.

feat: showMore message add event info

---

src/sass/toolbar.scss

This request is to add in a css change that helps fix toolbar wrapping when the display is too small. This issue was brought up [here - #1699](https://github.com/jquense/react-big-calendar/issues/1699). This should help cleanup some undesirable toolbar displays for mobile users. 
Bellow are some screenshots that show the issue I was describing. On mobile devices, if the selected date is too long then it will get wrapped beneath the "Today, Back, Next" buttons. This change will stack these three elements in a column for smaller display widths which helps it to look cleaner and prevents the button positions from shifting while scrolling through dates using the "next" button. Essentially, it will make all cases look like the second picture regardless of date length.

fix: changed flex-direction for rbc-toolbar mobile

---

stories/AboutBigCalendar.stories.mdx
stories/addons/addOns.stories.mdx
yarn.lock

docs: correct some linking

---

src/EventCell.js

The tabindex, applied to the event div, creates invalid ARIA component nesting
#2498

fix(ARIA): remove tabindex

---

src/utils/layout-algorithms/no-overlap.js

There are two events, A and B, with the same start and end times. In the month view, event A is displayed before event B. However, in the week and day views, event B is displayed before event A, causing inconsistent display results. After reviewing the code logic for handling event order in the day view, I have fixed this issue to ensure consistent display results across all views.

fix: day events sort fixed

---

src/TimeGridEvent.js
stories/Layout.stories.js
test/utils/DayEventLayout.test.js

This PR addresses two issues with how background events are rendered using both the `overlap` and `no-overlap` layout algorithms. I opted for the change I made due to its simplicity and the unlikelihood that it would have any adverse effects elsewhere in the calendar. It appears to me that the implementation of the `no-overlap` layout algorithm very deliberately returns different types for the `width` and `xOffset` style values than does the `overlap` algorithm; given this it seemed most reasonable to correct how those values are handled when rendering events in `TimeGridEvent`. 
I added two stories under "Additional Examples > Layout" to demonstrate the `overlap`/`no-overlap` behavior since that seemed like the most appropriate location for them.

fix overlapping background events, fixes #2452

---

CHANGELOG.md
package.json
src/utils/TimeSlots.js

This is a commit to fix[ issue 2536](https://github.com/jquense/react-big-calendar/issues/2536) and [2529](https://github.com/jquense/react-big-calendar/issues/2529).
When I was fixing [2529](https://github.com/jquense/react-big-calendar/issues/2529), I declared `slotMetrics` as a global variable, which caused all `DayColumn` instances to use the same instance of `slotMetrics`. This is also the reason why bug [ issue 2536](https://github.com/jquense/react-big-calendar/issues/2536) appears.
In this commit, I only modified the update timing of slotMetrics.Now both issues are resolved!
https://github.com/jquense/react-big-calendar/assets/63057542/756fc1b7-972e-4ef3-bb72-516e068218ac

fix: issue 2536

---

stories/props/date.mdx
stories/props/onSelectSlot.mdx
stories/props/onSelecting.mdx
stories/props/selected.mdx
stories/props/view.mdx

This is a commit to fix https://github.com/jquense/react-big-calendar/issues/2556 I also fixed other links in the docs that were not working.

fix(stories): fix not working links in docs

---

src/Selection.js

When `_handleTerminatingEvent` is executed, `_lastClickData` will no longer be cleared to trigger the `doubleClick` event.
This PR was created to fix [#2565](https://github.com/jquense/react-big-calendar/issues/2565).

fix: #2565 doubleClick

---

README.md
docs/README-ar.md

This contribution aims to improve the accessibility and reach of the React-Big-Calendar project by providing a translated version of the README file in Arabic. This will enable Arabic-speaking developers to easily understand the project, its features, and how to use it effectively.
- Increased accessibility: Makes the project more inclusive and welcoming to Arabic-speaking developers.
- Wider reach: Expands the potential user base and community of the project.
- Improved understanding: Enables Arabic speakers to easily comprehend the project's documentation and usage instructions.
1. The README file is translated into Arabic while maintaining the original formatting and structure.
2. The translated README is placed in a new "docs" folder at the root of the repository.
3. A link to the …

Translate README to Arabic

---

stories/demos/dragAndDrop.stories.mdx

This pull request closes #2584
After consulting the different examples provided as part of react Big Calendar, it came to my attention that the Drag and Drop Examples link is not functioning properly. When clicking on a link, it throws the an error message. 
I have changed the code to have the appropriate prop, which will link back to the correct section under AddOns section.
This PR removes the error and correctly links the Drag and Drop to its corresponding section in the App.

fix: fixing Drag and Drop Examples link

---

stories/demos/exampleCode/dnd.js

Fixes #2601. 
Added an if statement to account for the second case, and changed the updated state value to use the correct `allDay` value

fix bug with dnd drag drop

---

src/Agenda.js

Fix warning on agenda view
Version:
- "react": "18.2.0"
- "react-big-calendar": "1.13.0"
- "next": "14.2.4"

fix: warning defaultProps in Agenda

---

src/sass/styles.scss

This pull request addresses an issue with the calendar styling. The SCSS variables were not being applied correctly due to changes in Sass behavior. This PR updates the SCSS files to ensure the variables are applied correctly and resolves styling issues.
Warning in Console on Sass latest version:
`Sass's behavior for declarations that appear after nested rules will be changing to match the behavior specified by CSS in an upcoming version. To keep the existing behavior, move the declaration above the nested rule. To opt into the new behavior, wrap the declaration in & {}`
Changes Made:
Moved variable declarations to ensure that variables are declared before their rules

Fix: Sass warning on latest version

---

src/addons/dragAndDrop/EventContainerWrapper.js
src/addons/dragAndDrop/WeekWrapper.js
stories/demos/exampleCode/dndOutsideSource.js

Based on the work of @achrafl0 in https://github.com/jquense/react-big-calendar/pull/2616 and an attempt to fix https://github.com/jquense/react-big-calendar/issues/2383.
While testing I noticed that the current example is not quite correct.
The event is always triggered inside the calendar, and the only thing that prevents the event from being displayed in the month view is that it lacks a title (so only one line is displayed). This does not work in the week view because the time is known and so the event box is displayed. (You can see that if you drag over the day header column, a line is also displayed.
So I have made some changes in the example to avoid sending a `dragFromOutsideItem` at all, and added checks in the listeners accordingly.
Looking forward to your feedback.

fix(dnd): added check for null dragFromOutsideItem, updated example

---

src/Calendar.js
src/EventEndingRow.js
stories/Calendar.stories.js
stories/helpers/index.js
stories/props/components.mdx
stories/resources/customComponents.js

I'm trying to render a custom component for the `show more` button. I know there are a few recommended ways to do this through the `onShowMore` callback and the `messages.showMore` prop as suggested in #1147.
But that doesn't cover all use cases. For example, I want to access the events that are being hidden by the `show more` button. I also want to render a custom popup right next to the `show more` button.
This new component adds the following props:
- localizer
- slot
- slotDate
- count
- events
- remainingEvents
I can also update the types once this gets merged.
Resolves #2391
---
I tried reaching out through the Slack community first, but the invitation link has expired, could you post a new link?

feat(components): showMore component customization

---

src/Calendar.js
src/TimeGrid.js
src/TimeGridHeaderResources.js
src/sass/month.scss
src/sass/styles.scss
src/sass/time-grid.scss
stories/demos/exampleCode/resource.js
stories/props/resourceGroupingLayout.mdx
stories/props/resourceGroupingLayout.stories.js

Complete the missing parts of this [PR](https://github.com/jquense/react-big-calendar/pull/2652) and fix the UI width. 
I’m not sure why, but it seems to work well with a 141px header, possibly due to how the browser calculates the flexbox layout

Implement Conditional Resource Grouping

---

src/DateHeader.js

**Summary:**
According to [a11y](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/cell_role#description) - ARIA role cell is not allowed for a button element in the current context.
**Solution:**
Remove attribute **role="cell"** from a button element for the DateHeader component.

refactor(a11y): aria role cell is not allowed for button element

---

src/addons/dragAndDrop/EventContainerWrapper.js

When dragging an event from outsize of Calendar, the default of the size is 1 slot and having no way to customize this.
Example, for an event that we already know it takes 4 hours, the preview size could be 4 hours and movable around.
This PR was created to fix #2680

fix #2680 - Customize drag from outside event's length

---

stories/addons/dragAndDrop/props/API.stories.mdx
stories/addons/dragAndDrop/props/onDropFromOutside.mdx

Recording to [this](https://github.com/jquense/react-big-calendar/blob/fea41753a1d3e7b1140b5a94496eb035fa58d313/src/addons/dragAndDrop/EventContainerWrapper.js#L125)
The function dose return resource
A PR has already been created on [@type](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71224) as well

fix: update doc type of onDropFromOutside function signature to include resource parameter

---

README.md
src/Month.js
src/localizers/dayjs.js

this commit fixes the issues mentioned in #2534 
In cases of leap years, the month of March would often display unexpected off-range days / missing days entirely.
This includes special handling for leapyears, and does manual math to get the start of the week rather than Dayjs' `startOf`.

fix: issue #2534

---

stories/props/API.stories.mdx
stories/props/onSelectSlot.mdx
stories/props/onSelecting.mdx

Updated wording in `onSelecting` vs `onSelectSlot`difference section

docs: update phrasing for onSelectSlot parameter docs

---

src/addons/dragAndDrop/EventContainerWrapper.js

Fix my previous error from this PR: https://github.com/jquense/react-big-calendar/pull/2746
I was mistaken to add both _cleanup and this.reset() functions. Only one was necessary, the reset one.
This error appears, which it didn't appear during the testing part.
@cutterbl I am sorry about this. I saw it while trying to fork the library myself, didn't know when it would be merged :D 
It tries to cleanup an element that was already cleaned up, and so, the error appears.

Fix cleanup error
