jquense/react-big-calendar

package.json
Hi,
it's just a simple fix of your package.json (Url repo github is not good)
Thanks for this lib
=> fix url repo github

src/Calendar.jsx
Use the 'messages' props for the <Calendar /> component to pass the labels
as described in the PropTypes of <Calendar />
=> The Taskbar button labels can now be changed.

examples/demos/selectable.js
I was just going to change `mroe` to `more`, but I went ahead and made a few grammar tweaks too.
I'm excited to try and use this! I was dreading building a calendar.
=> Fix a typo in demos/selectable

src/Month.jsx
Add `.rbc-selected` according to `this.props.date`.
=> Add `.rbc-current` class to the "selected" date

README.md, examples/App.js, examples/Intro.md, examples/prism.less, examples/server.js, examples/styles.less, package.json, webpack/examples.config.es6.js
=> improve examples & doc

src/TimeGrid.jsx
=> propagate eventPropGetter to allDay row events

src/TimeColumn.jsx
Fixes #113 ? (I did not test but it definitively fixes that :) )
=> remove `.jsx` extension from import

examples/Api.js, package.json, src/Calendar.jsx, src/EventCell.jsx, src/Month.jsx
Went through the examples and fixed all unknown props warnings I could find. I am not familiar with the source yet, so there are probably a few more left to omit.
Please let me know if the approach is OK.
=> Fix unknown props warnings

examples/demos/customHeader.js, src/Calendar.jsx, src/Header.jsx, src/Month.jsx, src/TimeGrid.jsx
=> Adding optional custom Header component for month, week, day views

src/TimeColumn.jsx, src/TimeGrid.jsx, src/less/time-column.less, src/less/variables.less, src/utils/dates.js
Just updated version of https://github.com/intljusticemission/react-big-calendar/pull/132 according to your comment
=> Highlight today's columns

src/index.js
This PR addresses #257. Just let me know if there's anything else needed here!
=> Expose navigate constants

src/Calendar.js
=> Always navigate to day view when action is navigate.DATE

webpack/examples.config.js
otherwise examples runs at 8080
=> fix examples to match docs

src/Month.js
=> Pass messages prop to DateContentRow

src/addons/dragAndDrop/backgroundWrapper.js, src/addons/dragAndDrop/index.js
The DnD addon was reading event start/end times but wasn't using the startAccessor/endAccessor.
=> DnD: startAccessor and endAccessor support

src/localizers/moment.js
=> Fix time range format

src/utils/dayViewLayout.js
Change the sibbling detection and recognize all overlapping events
=> Siblings = overlapping events

.gitignore, src/BackgroundCells.js, src/BackgroundWrapper.js, src/Calendar.js, src/DateContentRow.js, src/DateHeader.js, src/Month.js, stories/Calendar.js
Trying to solve this issue https://github.com/intljusticemission/react-big-calendar/issues/224
=> Adding optional custom DateHeader component for month view

examples/Api.js, src/Calendar.js
=> use real flowtypes in API docs

src/DateHeader.js
This [typo](https://github.com/intljusticemission/react-big-calendar/issues/440)
=> Fixed typo on attribute name

src/Calendar.js
Add undocumented messages keys for localization.
=> Update Calendar.js - Add undocumented messages for localization

package.json
Pull Request to update peer dependencies to work with latest release of React (V16).
Resolves #573
=> Update peer dependencies to work with React V16

src/less/agenda.less
Potentially unhandled rejection [2] variable @cell-border is undefined in file /var/www/resources/assets/less/react-big-calendar/agenda.less line no. 10
=> Fix a Potentially unhandled rejection variable

src/Calendar.js
Resolves https://github.com/intljusticemission/react-big-calendar/issues/609 & https://github.com/intljusticemission/react-big-calendar/issues/503
=> Added 'onDrillDown' optional prop

src/Month.js
Avoid creating anonymous function, specially in the render method.
=> Avoid unecessary anonymous function

README.md
=> #390 write specific commands in README

examples/App.js, package.json, yarn.lock
This should get the examples running properly again.
=> update broken dependencies

examples/App.js, examples/demos/resource.js
I've added an example using the Resource settings for a multi-column daily view.
=> Added an example for Resource view

src/utils/dayViewLayout/index.js
In response to https://github.com/intljusticemission/react-big-calendar/pull/677#issuecomment-357525261. I think this is what you'd expect...
=> fix(dayViewLayout): container event check

README.md
There is now a channel in the Reactiflux Discord community for react-big-calendar (under libraries) so hopefully some of the easy questions can be answered there instead of flooding the backlog.
=> Add discord community channel information

src/addons/dragAndDrop/DropWrappers.js
I tried to fix #807 .
Please check this PR 🙏
=> Fixed DnD Add-on to use resourceID #807

examples/events.js, src/addons/dragAndDrop/DraggableEventWrapper.js, src/addons/dragAndDrop/withDragAndDrop.js
added $resizable to event fields which controls whether the resize anchors should be visible or not
=> per event resizability

src/less/toolbar.less
I've added all necessary changes into ```src/calendar.css```
https://codesandbox.io/s/5x6x7y8wlp
=> Improve toolbar responsiveness for mobile devices

examples/demos/dnd.js
This will help the people on using the onSelectSlot event.
=> Update to create events on select slot

src/localizers/moment.js
=> fix: different time format for multi day events when using moment

src/Calendar.js, src/Toolbar.js
Looked into a few submissions about the Toolbar not having an appropriate onView handler associated with a generated toolbar component. 
After some digging I noticed the 'onView' prop for the generated toolbar was named 'onViewChange'.
Corrected the prop name and seems to have cleared up the issue.
This is one of my first PR's so please advise if I am doing this totally wrong... Thanks
=> Fix toolbar

package-lock.json, package.json, src/Agenda.js, src/Calendar.js, src/DayColumn.js, src/EventEndingRow.js, src/EventRow.js, src/EventRowMixin.js, src/Toolbar.js, src/utils/TimeSlots.js, src/utils/messages.js, stories/Calendar.js
When in the agenda view, you often come across empty tables of events. This looks unfinished and is confusing to the user as it may appear that data has not loaded, rather than there is simply no data to display.
The solution is to display a message, informing the user that there are no events and the component is functioning correctly.
I think there may be a little bit of work to do in terms of styling/aligning the message. That said, I imagine most people are going to be adding their own project styles and therefore I feel it's okay to leave the styling basic and unopinionated.
=> Agenda no events msg

package.json
=> move @babel/cli to devDependencies

src/utils/TimeSlots.js
=> Fixed calculation of slots number for date when DST ends.

src/Calendar.js
This PR updates the docs to include all the custom component types as oppose to searching for this in the source code.
#1089
=> Docs: Update docs to include all custom components

src/TimeGrid.js, src/utils/Resources.js
The first commit fixes #1040, the second one fixes #1006
=> Update TimeGrid on resources list change

src/utils/Resources.js
Fixes https://github.com/intljusticemission/react-big-calendar/issues/1155
=> fix: duplicate events

src/ResourceHeader.js, src/TimeGridHeader.js, src/less/time-grid.less
Add an ability to set a custom resource headers. For #1174
=> Add ability to set custom resource headers

src/EventCell.js, src/less/event.less, yarn.lock
I've faced the same problem as @Kerumen described in #1173 as it was long time ago, I've decided to push pr with fix
=> Fix firefox event click bug

src/sass/variables.scss
This is a pretty minor pr, but nice to have.
=> redeclared all sass variables using !default

src/Selection.js
=> fix: ie fix for event bindings on unmounted components

src/index.js
I use date-fns and have custom localizer. Though I need to import
internals to create it. Would be good to have it in public api.
Also did you consider to use named exports instead of Object.assign?
=> Expose date localizer

src/EventCell.js, src/EventRowMixin.js, src/Popup.js
My team needs this for an issue with popovers displaying in multiple places on custom events.
=> Added continuesPrior and continuesAfter props to Event component

.size-snapshot.json, package.json, src/Agenda.js, src/DateContentRow.js, src/Month.js, src/Popup.js, src/Selection.js, src/TimeGrid.js, src/TimeGridHeader.js, yarn.lock
Ref https://github.com/react-bootstrap/dom-helpers/blob/master/CHANGELOG.md
Looks like this upgrade saved ~6kb in minified bundle. Will see how more
overlays upgrade will save.
=> Upgrade dom-helpers

src/TimeGrid.js
=> Make scrollToTime=00:00 working

src/utils/DayEventLayout.js
Without this patch, custom functions are ignored.
=> Fixes `dayLayoutAlgorithm` prop with custom function

src/localizers/date-fns.js
=> fix: moment format strings -> date-fns format strings

README.md
The old invite was putting joiners into an error state due to the Code of Conduct gate! Not ideal
=> Use main Reactiflux invite

package.json
=> Update react-overlays dependency

src/addons/dragAndDrop/WeekWrapper.js
Closes #1878  - broken selection in weekview views (incl month) - regressed in #1819.
=> fix(DnD): selection in WeekView

src/Selection.js
Added listener unregistration for #1940.
=> fix: Memory leak if Calendar is selectable #1940

src/Agenda.js
fix(Agenda): consider the start & end of the day to filter events
Fix: https://github.com/jquense/react-big-calendar/issues/1924
=> fix(Agenda): consider the start & end of the day to filter events

examples/demos/customView.js
Fix typo in custom view example
=> Typo in custom view

package.json, release.config.js
This properly commits the package.json update post publish
=> ci(release): Update to @semantic-release/git config

src/TimeGutter.js, src/less/time-grid.less, src/localizer.js, src/localizers/moment.js, src/sass/time-grid.scss, src/utils/TimeSlots.js, yarn.lock
This corrects #1617, fixing the display of the TimeGutter times as well as correcting event layouts from the momentLocalizer, while maintaining date math within the localizers.
=> fix: Correct display of beginning DST

.size-snapshot.json, examples/bundle.js, package.json, yarn.lock
Twitter has finally release an update to bootstrap-sass to resolve the math.div issues with current dart-sass versions.
=> chore: Update bootstrap-sass

.github/workflows/storybook.yml
=> fix: correct storybook deploy

src/BackgroundCells.js, src/DateContentRow.js, src/DayColumn.js, src/DayColumnWrapper.js, src/Month.js, src/TimeGrid.js
This corrects an issue where the TimeGutter is not properly calculating
=> fix: correct TimeGutter ref use

src/utils/layout-algorithms/no-overlap.js, stories/Layout.stories.js, stories/helpers/index.js
Thanks to D0HaTeJIJI0 for the fix here
#2110
=> fix: zero duration no-overlap events

.size-snapshot.json, src/sass/variables.scss
Remove requirement for SASS math plugin by doing the math ourselves
=> fix: do the math ourselves

src/addons/dragAndDrop/EventContainerWrapper.js
=> feat: use custom event wrapper when dragging

src/DayColumn.js
Have to roll back changes until we can refactor as functional component with hooks
=> fix: revert

src/addons/dragAndDrop/EventContainerWrapper.js
=> feat: allow using custom event wrapper component while dragging

src/TimeGrid.js
=> fix: do not autoscroll on event selection

src/TimeGrid.js
=> fix: auto scroll on event selection

src/Calendar.js, src/TimeGutter.js, stories/Calendar.stories.js, stories/resources/customComponents.js
Allows clients to override the time gutter wrapper.
This allows clients to override the time gutter with styling, custom groups etc.
=> feat(time-gutter-wrapper): expose time gutter wrapper component

src/utils/layout-algorithms/overlap.js
Minor adjustment to trigger a release
#2330
=> fix: set width

.github/workflows/release.yml
Maybe?
Still working out fix to release
=> ci: attempt resolution

src/utils/layout-algorithms/no-overlap.js
=> fix: no-overlap layout algorithm

.github/workflows/release.yml, src/Day.js
=> ci: update config

.github/workflows/release.yml
Attempt to use the semantic-release GitHub Action
=> ci: update action

.github/workflows/release.yml
=> ci: update configs

.github/workflows/release.yml, release.config.js
=> fix: correct publishing

.github/workflows/release.yml, release.config.js
=> ci: try again

.github/workflows/release.yml, release.config.js
=> ci: the old college try

package.json
=> ci: with publishConfig

.github/workflows/release.yml
=> ci: and another

.github/workflows/release.yml, release.config.js
=> ci: once again

.github/workflows/release.yml
=> ci: and again

package.json
=> ci: still trying

.github/workflows/release.yml
Fixed the publish script
https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
https://github.com/semantic-release/semantic-release/issues/1724#issuecomment-846090078
=> fix: Fixed publish script (fix #2330)

.github/workflows/storybook.yml
=> ci: update doc release

.gitignore, package.json, yarn.lock
=> ci: update Globalize

src/localizers/globalize.js
Revert 'globalize' dependency upgrade, and mark for future work
#2429
=> ci: revert globalize dependency upgrade messaging

src/TimeGridEvent.js
=> Made events accessible in week and day views

.scripts/build.mjs, src/Month.js, src/localizer.js, src/localizers/dayjs.js, src/localizers/luxon.js, src/localizers/moment.js, src/utils/eventLevels.js, stories/resources/events.js, yarn.lock
This changes the event sort used in the Month view to prioritize items in this order
* Multi Day events first
* Then all day events
* Then by start time
* Then by end time
=> feat(event sort): update event sort for multi day

CITATION.cff
Authors cited have 20 or more commits to Big Calendar
=> feat: add citation file

package.json, src/DayColumn.js, src/EventCell.js, src/TimeGridEvent.js, src/TimeGridHeader.js
This allow to detect backspace press on event
=> fix: replace deprecated onKeyPress by onKeyDown (allow detection of backspace on events)

src/DayColumn.js
Fixed an issue where component `DayColumn` would always update `slotMetrics` after the child component had finished rendering.
This causes the subcomponent to call `slotMetrics.getRange` with the properties `min` and `max` as before.
Here is the issue [#2529](https://github.com/jquense/react-big-calendar/issues/2529)
@cutterbl 
https://github.com/jquense/react-big-calendar/assets/63057542/7670001c-cd11-41df-856c-7093f52f0c4a
=> fix: issue 2529

README.md, docs/README-ar.md
=> docs: update Slack invite link

src/sass/styles.scss
Corrects an issue with improper nesting within SASS file
=> fix: correct nested sass

src/DayColumn.js, stories/props/dayPropGetter.mdx
=> feat(dayPropGetter): pass resourceId to method

stories/props/API.stories.mdx
=> Minor typo in API.stories.mdx

rollup.config.mjs
=> ci: correct json import for node 22

src/sass/toolbar.scss
=> fix(Toolbar): cursor styling on hover

package.json
This closes https://github.com/jquense/react-big-calendar/issues/2701
=> feat: add support for React 19
